feature v1.00
DusynHub/java-shareit pull request #1
Opened 2023-04-02 21:16 UTC by DusynHub

Реализована логика работы в соответствии с техническим заданием и добавлена документация для контроллеров и интерфейсов Добавлены аналогичные postman тесты и 3 новых теста для ItemController

2023-04-03 12:35 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 🔥

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@Data
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDTO add(@RequestHeader(value = "X-Sharer-User-Id")
`X-Sharer-User-Id` - лучше вынести в отдельный класс и сделать публичной константой, так как ни раз еще нам пригодится

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (userId == null) {
А зачем дополнительная проверка на `null` хэдера, если есть `@NotNull`?

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemDAOInMemory.java
> +        log.info(String.format("DAO: Удалерие предмета с id = '%d'", itemId));
```suggestion
        log.info(String.format("DAO: Удаление предмета с id = '%d'", itemId));
```

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDTO.java
> +    public ItemDTO(long id, String name, String description, Boolean available) {
Конструктор не используется, нужно удалить

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> + * Item в ItemDTO mapper
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Qualifier("ItemDaoInMemory")
Лишний, нужно удалить

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dao/ItemDAOInMemory.java
> +        Item itemToAdd = Item.builder()
Нужно вынести создание `Item` из `ItemDto` в `ItemMapper`

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    @Qualifier("ItemService")
Лишний, нужно удалить

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemPatch.java
> +public class ItemPatch {
Кстати, patch можно тоже очень легко сделать с помощью `@MappingTarget` от `mapstruct`

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    @Qualifier("UserServiceImpl")
Лишний, нужно удалить

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +    public UserDTO() {
`@NoArgsConstuctor`

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +    public UserDTO(long id, String name, String email) {
Похоже, что не используется - нужно удалить

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDTO.java
> +    public ItemDTO() {
`@NoArgsConstuctor`

2023-04-03 12:35 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    @Order(1)
Лучше постараться настроить тесты таким образом, чтобы не приходилось запусть их в определенном порядке

2023-04-07 11:06 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@Data
Убрал использование `@Data`

2023-04-07 11:07 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDTO add(@RequestHeader(value = "X-Sharer-User-Id")
Вынес в отдельный класс в пакете ru/practicum/shareit/item/util

2023-04-07 11:07 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (userId == null) {
Убрал лишнюю проверку

2023-04-07 11:08 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/dao/ItemDAOInMemory.java
> +        log.info(String.format("DAO: Удалерие предмета с id = '%d'", itemId));
Ошибка в слове исправлена

2023-04-07 11:09 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/dto/ItemDTO.java
> +    public ItemDTO(long id, String name, String description, Boolean available) {
Классы DTO переработаны, лишние конструкторы удалил

2023-04-07 11:09 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> + * Item в ItemDTO mapper
Добавил использование библиотеки MapStruct

2023-04-07 11:09 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    @Qualifier("ItemDaoInMemory")
Удалил лишнюю аннотацию

2023-04-07 11:10 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/dao/ItemDAOInMemory.java
> +        Item itemToAdd = Item.builder()
Перенес в ItemMapper

2023-04-07 11:11 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    @Qualifier("ItemService")
Удалил лишнюю аннтоацию

2023-04-07 11:12 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/dto/ItemPatch.java
> +public class ItemPatch {
Исключил этот класс. В текущей функциональности лишний.

2023-04-07 11:12 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    @Qualifier("UserServiceImpl")
Удалил лишнюю аннтоацию

2023-04-07 11:12 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +    public UserDTO() {
Переработал DTO классы

2023-04-07 11:13 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +    public UserDTO(long id, String name, String email) {
Переработал DTO классы

2023-04-07 11:13 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/dto/ItemDTO.java
> +    public ItemDTO() {
Переработал DTO классы

2023-04-07 11:13 UTC, DusynHub commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +class ItemControllerTest {
Сделал тесты независимыми от порядка запуска и сгруппировал по методам контроллеров

2023-04-07 11:14 UTC, DusynHub commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    @Order(1)
Сделал тесты независимыми от порядка запуска и сгруппировал по методам контроллеров

2023-04-07 11:55 UTC, closed without merging