feature/add-bookings-v.1.0.0
DusynHub/java-shareit pull request #3
Opened 2023-04-25 14:14 UTC by DusynHub

- удалены классы валидаторы Item и User
- реализованы фичи в соответствиями с требованиями тестов и техничесого задания

2023-04-26 10:52 UTC, AnastasiyaFomkina requested changes

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Service/BookingService.java
> +    @Transactional(propagation = Propagation.NEVER)
А зачем `@Transactional` над методами интерфейса?
Вот здесь можно почитать про [@Transactional](https://habr.com/ru/articles/532000/) под капотом. Предлагаю все таки проставлять под конкретными методами сервиса

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                @Valid @NotNull @Positive Long userId,
Предлагаю использовать [@Validated](https://reflectoring.io/bean-validation-with-spring-boot/#validating-path-variables-and-request-parameters:~:text=WebMvcTest%20annotation.-,Validating%20Path%20Variables%20and%20Request%20Parameters,-Validating%20path%20variables)

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutputDto.java
> +    public ItemOutputDtoForBooking item;
А почему `public`? Лучше максимально скрывать все поля, а для доступа к ним использовать getter и setter. Нужно переделать

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutputDtoForItem.java
> +    long bookerId;
У полей не хватает модификаторов доступа

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
Мы пока не проходили `@EqualsAndHashCode` для jpa сущностей. Удали, пожалуйста, везде по проекту

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking() {
Можно заменить на [@NoArgsConstructor](https://habr.com/ru/companies/piter/articles/676394/#:~:text=.surname%20%3D%20surname%3B%0A%20%20%20%20%7D%0A%7D-,%40NoArgsConstructor,-%2C%C2%A0%40RequiredArgsConstructor%2C%C2%A0%40AllArgsConstructor)

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +@Mapper
Лучше [сделать маппер компонентом спринга](https://www.baeldung.com/mapstruct#:~:text=Mapping%20With%20Dependency%20Injection), тогда его можно будет инжектить, как любой другой спринговый бин
Предлагаю поправить для всех мапперов в проекте

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @FutureOrPresent
Валидировать сущность уже лишнее, так как вся валидация должна быть на уровне dto, после чего все невалидные данные будут отсеяны

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInputDto.java
> +    private LocalDateTime start;
_Саморазвитие_
Для полей с датой лучше использовать [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates), чтобы точно указать из какого паттерна даты мы будем парсить значение. Так получитися избежать ошибок парсинга json-даты в объект

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Page<Booking> getBookingByOwnerFirstNext(@Param("itemId") Long itemId, @Param("userId") Long userId, Pageable page);
Лучше возвращать `List`, так как после мы просто кастуем `Page` в `List` и никак его не используем. Если мы сразу будем возвращать `List`, спринг самостоятельно вернет нам список размера `pageble.size`
Поправь, пожалуйста, для всех запросов с пагинацией

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +        requestState = getState(state);
Нет смысла разбивать на две строчки
```suggestion
        State requestState = getState(state);
```

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +            case ALL:
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +            case ALL:
И здесь тоже хорошо помогут паттеры

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +    private static State getState(String state) {
Лучше перенести метод в `enum State` и упростить с помощью [valueOf()](https://vertex-academy.com/tutorials/ru/perechisleniya-enum-java-2/#:~:text=%D0%9C%D0%B5%D1%82%D0%BE%D0%B4-,valueOf(),-%2D%20%D0%BF%D0%BE%D0%B7%D0%B2%D0%BE%D0%BB%D1%8F%D0%B5%D1%82%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F)

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ru.practicum.shareit.comment.dto.CommentOutputDto addComment(Long userId, Long itemId, Comment comment);
Нужно убрать полное название пути:
```suggestion
    CommentOutputDto addComment(Long userId, Long itemId, Comment comment);
```

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +import java.util.*;
Лучше не использовать `wildcard` в импортах.
По вот этой [статье](https://struchkov.dev/blog/using-wildcard-imports-in-java/) можно настроить IDEA, чтобы избавиться от `*`

2023-04-26 10:52 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-05-02 00:15 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/Service/BookingService.java
> +    @Transactional(propagation = Propagation.NEVER)
Убрал лишние аннотации, оставил только нужные в классах-имплементациях

2023-05-02 00:16 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                @Valid @NotNull @Positive Long userId,
Использовал `@Validated` для активации проверок

2023-05-02 00:24 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutputDto.java
> +    public ItemOutputDtoForBooking item;
Ошибся, переделывал поля и ошибся в модификаторах при исправлениях. Исправил

2023-05-02 00:24 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/dto/BookingOutputDtoForItem.java
> +    long bookerId;
Ошибся, переделывал поля и ошибся в модификаторах при исправлениях. Исправил

2023-05-02 00:25 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@EqualsAndHashCode
Убрал эту аннотацияю из сущностей

2023-05-02 00:25 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking() {
Использовал аннтоацию

2023-05-02 00:31 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public Booking(Long id,
Добавил аннотацию в сущности

2023-05-02 00:31 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +@Mapper
Добавил маппераы в компоненты спринга

2023-05-02 00:31 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private String status;
Исправил поле на enum

2023-05-02 00:32 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/Service/BookingService.java
Проглядел, исправил

2023-05-02 00:32 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @FutureOrPresent
Убрал валидацию из сущностей

2023-05-02 00:32 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/dto/BookingInputDto.java
> +    private LocalDateTime start;
Добавил формат перевода даты

2023-05-02 00:33 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    Page<Booking> getBookingByOwnerFirstNext(@Param("itemId") Long itemId, @Param("userId") Long userId, Pageable page);
Изменил тип возвращаемого результат

2023-05-02 00:34 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +        requestState = getState(state);
Испарвил ошибочное разделение объявления и инициализации переменной

2023-05-02 00:35 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +            case ALL:
Добавил возможную реализацию. Решил классы-звенья цепи сделать вложенными классами. 
Не знаю насколько это корректно.

2023-05-02 00:35 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +            case ALL:
Добавил возможную реализацию. Решил классы-звенья цепи сделать вложенными классами. 
Не знаю насколько это корректно.

2023-05-02 00:35 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +    private static State getState(String state) {
Перенёс метод в `enum State`

2023-05-02 00:35 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    ru.practicum.shareit.comment.dto.CommentOutputDto addComment(Long userId, Long itemId, Comment comment);
Исправил ошибку

2023-05-02 00:35 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +import java.util.*;
Убрал `wildcard` из импортов

2023-05-02 00:36 UTC, DusynHub commented on src/main/resources/schema.sql
> +
Пока не стал добавлять, так как не очень понимаю по каким полям индекс составлять.

2023-05-02 07:44 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Service/BookingServiceImpl.java
> +            case ALL:
Отличная реализация - молодец  🔥
Я бы все таки звенья вынесла бы в отдельные классы, так как они могут разрастаться и сильно перегружать основной класс, но в нашем случае можно оставить и вложенными, так как больше расширять мы их не будем

2023-05-02 07:45 UTC, AnastasiyaFomkina approved these changes

2023-05-02 12:21 UTC, merged