Добавлен функционал в соответствии с ТЗ и тесты
DusynHub/java-shareit pull request #4
Opened 2023-05-14 00:19 UTC by DusynHub

…ервисов

2023-05-14 10:13 UTC, AnastasiyaFomkina requested changes
Привет! Нужно удалить все лишние файлы из пулл реквеста и добавить папку `htmlReport` в игнорирование `.gitginore`

2023-05-14 11:54 UTC, AnastasiyaFomkina requested changes
Привет! Отличная работа - молодец. Клево, что написал так много подробных тестов 👍
Давай постараемся максимально избавиться от дублирований кода и немного сократить работу. В комментариях предложила несколько решений, как оптимизировать тесты и сделать их более читаемыми

2023-05-14 11:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> + * TODO Sprint add-item-requests.
Забыл удалить TODO

2023-05-14 11:54 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> + * TODO добавить описание интерфейса
И здесь

2023-05-14 11:54 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        void getBookingsByBooker_InvalidFrom_thenReturnException() {
Некоторые тесты можно объединить в один [параметризованный тест](https://www.baeldung.com/parameterized-tests-junit-5). Так можно избежать множественных повторений одних и тех же проверок

2023-05-14 11:54 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/controller/ItemRequestControllerTest.java
> +                            .header("X-Sharer-User-Id", requesterId))
Лучше использовать уже готовую константу. Можно быстро заменить использование по всему проекту с помощью сочетания клавиш [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html#replace_search_string_in_project:~:text=them%20with%20commas.-,Replace%20the%20search%20string,-in%20a%20project)

2023-05-14 11:54 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
Предлагаю немного подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2023-05-14 11:54 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +            User user3 = User.builder()
Нужно максимально избавиться от дублирований в тестах. Все повторяющиеся объекты вынести в BeforeEach, а проверки  - в отдельные методы

2023-05-14 17:37 UTC, DusynHub commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +            User user3 = User.builder()
Постарался вынести все инициализации переменных, используемые в тестах, в метод метод` beforeEach()`

2023-05-14 17:38 UTC, DusynHub commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
Тесты разделены по методам тестируемого класса с помощью `@Nested`. Необходимо дополнительно разделить?

2023-05-14 17:38 UTC, DusynHub commented on src/test/java/ru/practicum/shareit/request/controller/ItemRequestControllerTest.java
> +                            .header("X-Sharer-User-Id", requesterId))
Заменил заголовок на переменную во всех тестах

2023-05-14 17:39 UTC, DusynHub commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        void getBookingsByBooker_InvalidFrom_thenReturnException() {
Спасибо за рекомендацию использовать параметризированный тест. 
Использовал для сокращения тестов.

2023-05-14 17:40 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> + * TODO добавить описание интерфейса
Доработал описание

2023-05-14 17:40 UTC, DusynHub commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> + * TODO Sprint add-item-requests.
Доработал описание

2023-05-15 09:55 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
Нет, все ок. Не обратила внимание на то, что уже все есть. Прости, пожалуйста

2023-05-15 09:56 UTC, AnastasiyaFomkina approved these changes
Огонь 🔥

2023-05-15 10:28 UTC, merged